export enum ParasiteType {
  ASCARIS_LUMBRICOIDES = 'ASCARIS LUMBRICOIDES',
  ENTEROBIUS_VERMICULARIS = 'ENTEROBIUS VERMICULARIS',
  TRICHURIS_TRICHIURA = 'TRICHURIS TRICHIURA',
  ANCYLOSTOMA = 'ANCYLOSTOMA',
  TAENA_SP = 'TAENA SP',
  HYMENOLEPIS_NANA = 'HYMENOLEPIS NANA',
  HYMENOLEPIS_DIMUTA = 'HYMENOLEPIS DIMUTA'
}

export enum ProtozooType {
  BLASTOCYSTIS_HOMINIS = 'BLASTOCYSTIS HOMINIS',
  ENTAMOEBA_COLI = 'ENTAMOEBA COLI',
  ENTAMOEBA_HARTMANNI = 'ENATMOEBA HARTMANNI',
  ENTAMOEBA_HISTOLYTICA = 'ENTAMOEBA HISTOLYTICA',
  GIARDIA_DUODENALIS = 'GIARDIA DUODENALIS',
  CHILOMASTIX_MESNILI = 'CHILOMASTIX MESNILI',
  ENDOLIMAX_NANA = 'ENDOLIMAX NANA',
  IODAMOEBA_BUTSCHLII = 'IODAMOEBA BUTSCHLII',
  URBANORUM_SPP = 'URBANORUM SPP'
}

export enum StoolColor {
  AMARILLO = 'Amarillo',
  NEGRO = 'Negro',
  BLANCO = 'Blanco',
  CAFE = 'Café',
  VERDE = 'Verde',
  ROJO = 'Rojo'
}

export enum StoolConsistency {
  BLANDA = 'Blanda',
  FORMADA = 'Formada',
  PASTOSA = 'Pastosa',
  LIQUIDA = 'Liquida',
  DIARREICA = 'Diarreica'
}

export enum StoolShape {
  ESCASO = 'Escaso',
  MODERADO = 'Moderado',
  ABUNDANTE = 'Abundante'
}
