import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, FormArray, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { StoolTestService } from '../../../services/stool-test.service';
import { PatientService } from '../../../services/patient.service';
import { DoctorService } from '../../../services/doctor.service';
import { AuthService } from '../../../services/auth.service';
import { Patient } from '../../../models/patient.interface';
import { Doctor } from '../../../models/doctor.interface';
import { ParasiteType, ProtozooType, StoolColor, StoolConsistency, StoolShape } from '../../../enums/stool-test.enums';
import { EscasaModeradaAbundanteAusenteQuantity } from '../../../enums/escasa-moderada-abundante-ausente.enums';
import { TestStatus } from '../../../enums/test-status.enums';
import { CreateStoolTestDto, StoolTest, UpdateStoolTestDto } from '../../../models/stool-test.interface';
import { ParasiteResult, ProtozooResult } from '../../../models/stool-test.interfaces';
import { PatientQuickCreateModalComponent } from '../../patient/patient-form/patient-quick-create-modal.component';
import { DoctorQuickCreateModalComponent } from '../../../shared/modals/doctor-quick-create-modal.component';
import { GenresLabels } from '../../../enums/genres.enums';

@Component({
  selector: 'app-stool-test-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, PatientQuickCreateModalComponent, DoctorQuickCreateModalComponent],
  templateUrl: './stool-test-form.component.html',
  styleUrls: ['./stool-test-form.component.css']
})
export class StoolTestFormComponent implements OnInit {
  @ViewChild(PatientQuickCreateModalComponent) patientModal!: PatientQuickCreateModalComponent;
  @ViewChild(DoctorQuickCreateModalComponent) doctorModal!: DoctorQuickCreateModalComponent;
  
  private validateStoolColor(value: string | undefined): StoolColor | undefined {
    if (!value) return undefined;
    return value as StoolColor;
  }

  private validateStoolConsistency(value: string | undefined): StoolConsistency | undefined {
    if (!value) return undefined;
    return value as StoolConsistency;
  }

  private validateStoolShape(value: string | undefined): StoolShape | undefined {
    if (!value) return undefined;
    return value as StoolShape;
  }

  private validateEscasaModeradaAbundanteAusenteQuantity(value: string | undefined): EscasaModeradaAbundanteAusenteQuantity | undefined {
    if (!value) return undefined;
    return value as EscasaModeradaAbundanteAusenteQuantity;
  }


  stoolTestForm!: FormGroup;
  isEditMode = false;
  testId?: number;
  loading = false;
  saving = false;
  generatingSample = false;
  loadingPatients = false;
  loadingDoctors = false;
  errorMessage = '';
  successMessage = '';

  patients: Patient[] = [];
  doctors: Doctor[] = [];
  selectedPatient: Patient | null = null;
  currentStoolTest: StoolTest | null = null;

  // Enum arrays for templates
  stoolColors = Object.values(StoolColor);
  stoolConsistencies = Object.values(StoolConsistency);
  stoolShapes = Object.values(StoolShape);
  stoolEscasaModeradaAbundanteAusenteQuantities = Object.values(EscasaModeradaAbundanteAusenteQuantity);
  parasiteTypes = Object.values(ParasiteType);
  protozooTypes = Object.values(ProtozooType);

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private stoolTestService: StoolTestService,
    private patientService: PatientService,
    private doctorService: DoctorService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.initializeForm();
    this.loadPatients();
    this.loadDoctors();

    // Check if we're in edit mode
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.testId = +params['id'];
        this.isEditMode = true;
        this.loadTestData(this.testId);
      } else {
        // Set default values for new test
        const now = new Date();
        const localDateTime = now.toISOString().slice(0, 16);
        this.stoolTestForm.patchValue({
          testDate: localDateTime,
          status: 'pending'
        });
        // sampleNumber will be generated by backend
      }
    });
  }

  initializeForm(): void {
    this.stoolTestForm = this.fb.group({
      // Patient Information
      patientId: ['', Validators.required],
      patientName: [''],
      patientAge: [''],
      patientSex: [''],

      // Test Information
      sampleNumber: [''],
      doctorId:[''],
      testDate: [new Date().toISOString().slice(0, 16)], // Fecha actual
      status: [TestStatus.PENDING],

      // Physical Examination - Valores normales preseleccionados
      color: ['Café'], // Color café es el más común en heces normales
      consistency: ['Formada'], // Consistencia formada es lo normal
      shape: ['Moderado'], // Cantidad moderada es lo típico
      mucus: ['No se observa'], // Normal es no observar mucosidad

      // Microscopic Examination - Valores normales preseleccionados
      leukocytes: ['No se observa'], // Normal es no observar leucocitos
      erythrocytes: ['No se observa'], // Normal es no observar eritrocitos
      parasites: this.fb.array([]), // Normal es no tener parásitos
      protozoos: this.fb.array([]), // Normal es no tener protozoos

      // Observations
      observations: ['']
    });
  }

  createParasiteGroup(): FormGroup {
    return this.fb.group({
      type: [''], // El usuario debe seleccionar el tipo de parásito
      quantity: [''] // El usuario debe especificar la cantidad
    });
  }

  createProtozooGroup(): FormGroup {
    return this.fb.group({
      type: [''], // El usuario debe seleccionar el tipo de protozoo
      quantity: [''] // El usuario debe especificar la cantidad
    });
  }

  get parasitesArray(): FormArray {
    return this.stoolTestForm.get('parasites') as FormArray;
  }

  get protozoosArray(): FormArray {
    return this.stoolTestForm.get('protozoos') as FormArray;
  }

  getParasiteGroup(index: number): FormGroup {
    return this.parasitesArray.at(index) as FormGroup;
  }

  getProtozooGroup(index: number): FormGroup {
    return this.protozoosArray.at(index) as FormGroup;
  }

  addParasite(): void {
    this.parasitesArray.push(this.createParasiteGroup());
  }

  removeParasite(index: number): void {
    if (this.parasitesArray.length > 1) {
      this.parasitesArray.removeAt(index);
    }
  }

  addProtozoo(): void {
    this.protozoosArray.push(this.createProtozooGroup());
  }

  removeProtozoo(index: number): void {
    if (this.protozoosArray.length > 1) {
      this.protozoosArray.removeAt(index);
    }
  }

  loadPatients(): void {
    this.loadingPatients = true;
    this.patientService.getPatients(1, 1000).subscribe({
      next: (response) => {
        const patients = Array.isArray(response?.data) ? response.data : [];
        this.patients = patients.filter(p => p.isActive);
        this.loadingPatients = false;
      },
      error: (error) => {
        console.error('Error loading patients:', error);
        this.errorMessage = 'Error al cargar la lista de pacientes';
        this.loadingPatients = false;
      }
    });
  }

  loadDoctors(): void {
    this.loadingDoctors = true;
    this.doctorService.getDoctors(1, 1000).subscribe({
      next: (response) => {
        const doctors = Array.isArray(response?.data) ? response.data : [];
        this.doctors = doctors;
        this.loadingDoctors = false;
      },
      error: (error) => {
        console.error('Error loading doctors:', error);
        this.errorMessage = 'Error al cargar la lista de médicos';
        this.loadingDoctors = false;
      }
    });
  }

  onPatientSelected(): void {
    const patientId = this.stoolTestForm.get('patientId')?.value;
    if (!patientId) {
      this.selectedPatient = null;
      this.stoolTestForm.patchValue({
        patientName: '',
        patientAge: '',
        patientSex: ''
      });
      return;
    }

    this.selectedPatient = this.patients.find(p => p.id === patientId) || null;
    
    if (this.selectedPatient) {
      this.stoolTestForm.patchValue({
        patientName: this.selectedPatient.name,
        patientAge: this.selectedPatient.age,
        patientSex: this.selectedPatient.sex
      });
    }
  }

  loadTestData(id: number): void {
    this.loading = true;
    this.stoolTestService.getStoolTestById(id).subscribe({
      next: (test: StoolTest) => {
        // Set patient first
        this.stoolTestForm.patchValue({
          patientId: test.patientId,
          patientName: test.patient.name,
          patientAge: test.patient.age,
          patientSex: test.patient.sex,
          sampleNumber: test.sampleNumber,
          testDate: test.testDate ? new Date(test.testDate).toISOString().slice(0, 16) : '',
          status: test.status,
          color: test.color,
          consistency: test.consistency,
          shape: test.shape,
          mucus: test.mucus,
          leukocytes: test.leukocytes,
          erythrocytes: test.erythrocytes,
          observations: test.observations || ''
        });

        // Load parasites
        if (test.parasites && test.parasites.length > 0) {
          this.parasitesArray.clear();
          test.parasites.forEach(parasite => {
            this.parasitesArray.push(this.fb.group({
              type: [parasite.type],
              quantity: [parasite.quantity]
            }));
          });
        }

        // Load protozoos
        if (test.protozoos && test.protozoos.length > 0) {
          this.protozoosArray.clear();
          test.protozoos.forEach(protozoo => {
            this.protozoosArray.push(this.fb.group({
              type: [protozoo.type],
              quantity: [protozoo.quantity]
            }));
          });
        }
        this.currentStoolTest = test;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading test data:', error);
        this.errorMessage = 'Error al cargar los datos del examen';
        this.loading = false;
      }
    });
  }

  generateSampleNumber(): void {
    this.generatingSample = true;
    
    this.stoolTestService.getNextSampleNumber().subscribe({
      next: (response) => {
        this.stoolTestForm.patchValue({
          sampleNumber: response.sampleNumber
        });
        this.generatingSample = false;
      },
      error: () => {
        // Fallback: generate locally
        const now = new Date();
        const year = now.getFullYear().toString().slice(-2);
        const month = (now.getMonth() + 1).toString().padStart(2, '0');
        const day = now.getDate().toString().padStart(2, '0');
        const hours = now.getHours().toString().padStart(2, '0');
        const minutes = now.getMinutes().toString().padStart(2, '0');
        const seconds = now.getSeconds().toString().padStart(2, '0');
        
        const sampleNumber = `STOOL-${year}-${month}${day}-${hours}${minutes}${seconds}`;
        
        this.stoolTestForm.patchValue({
          sampleNumber: sampleNumber
        });
        this.generatingSample = false;
      }
    });
  }

  onSubmit(): void {
    if (!this.stoolTestForm.valid) {
      Object.keys(this.stoolTestForm.controls).forEach(key => {
        this.stoolTestForm.get(key)?.markAsTouched();
      });
      this.errorMessage = 'Por favor complete todos los campos requeridos';
      return;
    }

    this.saving = true;
    this.errorMessage = '';
    this.successMessage = '';

    const formValue = this.stoolTestForm.getRawValue();

    // Prepare parasites array
    const parasites: ParasiteResult[] = formValue.parasites
      .filter((p: any) => p.type && p.type !== '')
      .map((p: any) => ({
        type: p.type,
        quantity: p.quantity || 'N/A'
      }));

    // Prepare protozoos array
    const protozoos: ProtozooResult[] = formValue.protozoos
      .filter((p: any) => p.type && p.type !== '')
      .map((p: any) => ({
        type: p.type,
        quantity: p.quantity || 'N/A'
      }));

    if (this.isEditMode && this.testId) {
      // Update existing test
      const updateDto: UpdateStoolTestDto = {
        sampleNumber: formValue.sampleNumber || undefined,
        doctorId: formValue.doctorId || undefined,
        color: formValue.color || undefined,
        consistency: formValue.consistency || undefined,
        shape: formValue.shape || undefined,
        mucus: formValue.mucus || undefined,
        leukocytes: formValue.leukocytes || undefined,
        erythrocytes: formValue.erythrocytes || undefined,
        parasites: parasites.length > 0 ? parasites : undefined,
        protozoos: protozoos.length > 0 ? protozoos : undefined,
        testDate: formValue.testDate || undefined,
        observations: formValue.observations || undefined,
        status: formValue.status || undefined
      };

      this.stoolTestService.updateStoolTest(this.testId, updateDto).subscribe({
        next: (updatedTest) => {
          this.saving = false;
          this.successMessage = 'Examen actualizado exitosamente';
          
          setTimeout(() => {
            this.router.navigate(['/stool-tests', updatedTest.id]);
          }, 1500);
        },
        error: (error) => {
          this.saving = false;
          this.errorMessage = error.message || 'Error al actualizar el examen';
          console.error('Error updating stool test:', error);
        }
      });
    } else {
      // Create new test - Include createdById from authenticated user
      const currentUser = this.authService.getCurrentUserValue();
      
      const createDto: CreateStoolTestDto = {
        patientId: formValue.patientId.toString(),
        doctorId: formValue.doctorId || undefined,
        color: formValue.color || undefined,
        consistency: formValue.consistency || undefined,
        shape: formValue.shape || undefined,
        mucus: formValue.mucus || undefined,
        leukocytes: formValue.leukocytes || undefined,
        erythrocytes: formValue.erythrocytes || undefined,
        parasites: parasites.length > 0 ? parasites : undefined,
        protozoos: protozoos.length > 0 ? protozoos : undefined,
        testDate: formValue.testDate || undefined,
        observations: formValue.observations || undefined,
        status: formValue.status || undefined,
        createdById: currentUser?.id || undefined // UUID del usuario que crea el examen
      };

      // 🔍 LOG: Verificar el objeto antes de enviar
      console.log('📝 FORMULARIO - Objeto CreateStoolTestDto construido:', createDto);
      console.log('🔍 FORMULARIO - ¿Tiene doctorId?', 'doctorId' in createDto, 'Valor:', createDto.doctorId);
      console.log('🔍 FORMULARIO - ¿Tiene createdById?', 'createdById' in createDto, 'Valor:', createDto.createdById);
      console.log('📋 FORMULARIO - Usuario autenticado:', {
        id: currentUser?.id,
        idType: typeof currentUser?.id,
        username: currentUser?.username,
        email: currentUser?.email,
        role: currentUser?.role
      });

      this.stoolTestService.createStoolTest(createDto).subscribe({
        next: (createdTest) => {
          this.saving = false;
          this.successMessage = 'Examen creado exitosamente';
          
          setTimeout(() => {
            this.router.navigate(['/stool-tests', createdTest.id]);
          }, 1500);
        },
        error: (error) => {
          this.saving = false;
          // Mostrar el mensaje de error detallado del backend si está disponible
          if (error.error && error.error.message) {
            if (Array.isArray(error.error.message)) {
              this.errorMessage = error.error.message.join(', ');
            } else {
              this.errorMessage = error.error.message;
            }
          } else {
            this.errorMessage = error.message || 'Error al crear el examen';
          }
          console.error('Error creating stool test:', error);
          // Mostrar los detalles del error para debugging
          if (error.error) {
            console.error('Backend error details:', error.error);
            if (Array.isArray(error.error.message)) {
              console.error('Validation errors:', error.error.message);
            }
          }
        }
      });
    }
  }

  openPatientModal(): void {
    this.patientModal.open();
  }

  onPatientCreated(newPatient: Patient): void {
    // Agregar el nuevo paciente a la lista
    this.patients.push(newPatient);
    
    // Ordenar la lista alfabéticamente por nombre
    this.patients.sort((a, b) => 
      a.name.localeCompare(b.name)
    );

    // Seleccionar automáticamente el nuevo paciente
    this.stoolTestForm.patchValue({
      patientId: newPatient.id
    });

    // Actualizar los datos del paciente en el formulario
    this.onPatientSelected();

    // Mostrar mensaje de éxito
    this.successMessage = `Paciente "${newPatient.name}" creado y seleccionado exitosamente`;
    
    // Limpiar mensaje después de 3 segundos
    setTimeout(() => {
      this.successMessage = '';
    }, 3000);
  }

  onModalClosed(): void {
    // Este método se llama cuando el modal se cierra sin crear un paciente
    // Puede dejarse vacío o agregar lógica adicional si es necesario
  }

  openDoctorModal(): void {
    this.doctorModal.openModal();
  }

  onDoctorCreated(newDoctor: Doctor): void {
    // Agregar el nuevo médico a la lista
    this.doctors.push(newDoctor);
    
    // Ordenar la lista alfabéticamente por apellido
    this.doctors.sort((a, b) => 
      a.lastName.localeCompare(b.lastName)
    );

    // Seleccionar automáticamente el nuevo médico
    this.stoolTestForm.patchValue({
      doctorId: newDoctor.id
    });

    // Mostrar mensaje de éxito
    this.successMessage = `Médico "${newDoctor.firstName} ${newDoctor.lastName}" creado y seleccionado exitosamente`;
    
    // Limpiar mensaje después de 3 segundos
    setTimeout(() => {
      this.successMessage = '';
    }, 3000);
  }

  getGenreLabel(genre: string): string {
    return GenresLabels[genre as keyof typeof GenresLabels] || genre;
  }

  goBack(): void {
    this.router.navigate(['/stool-tests']);
  }
}
